name: Release Plugin

on:
  push:
    # Trigger workflow on tag push (e.g., git tag v1.0 && git push origin v1.0)
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Build IntelliJ Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildPlugin

      - name: Determine Plugin ZIP
        id: find_zip
        shell: bash
        run: |
          set -euo pipefail
          ZIP_PATH=$(ls -1t build/distributions/*.zip | head -n 1)
          if [ ! -f "$ZIP_PATH" ]; then
            echo "No plugin ZIP found in build/distributions" >&2
            exit 1
          fi
          echo "ZIP_PATH=$ZIP_PATH" >> "$GITHUB_ENV"
          echo "ZIP_NAME=$(basename "$ZIP_PATH")" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Plugin ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_PATH }}
          asset_name: ${{ env.ZIP_NAME }}
          asset_content_type: application/zip
